### ISSUE TITLE
Support new stage Beta 3 for 4.8.0 in qa-integration-framework repository

### ISSUE THREAD

**Issue by rauldpm** [wazuh/qa-integration-framework#109]
## Description

This issue attempts to support a new stage Beta 3 for 4.8.0 in the qa-integration-framework repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on qa-integration-framework repository.
- [ ] Create tag v4.8.0-beta3 from branch 4.8.0 on qa-integration-framework repository.
- [ ] Create and publish a pre-release:
