### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in qa-integration-framework repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/qa-integration-framework#191]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the qa-integration-framework repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on qa-integration-framework repository.
- [ ] Create tag v4.9.0-alpha1 from branch 4.9.0 on qa-integration-framework repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.9.0-alpha1.
