### ISSUE TITLE
Support new stage RC 1 for 4.8.1 in qa-integration-framework repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/qa-integration-framework#193]
## Description

This issue attempts to support a new stage RC 1 for 4.8.1 in the qa-integration-framework repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.1 (if applicable).
- [ ] Bump revision for branch 4.8.1 on qa-integration-framework repository.
- [ ] Create tag v4.8.1-rc1 from branch 4.8.1 on qa-integration-framework repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.8.1-rc1.
