### ISSUE TITLE
Refactor and migrate active response IT framework dependencies from QA repository

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/qa-integration-framework#2]
| Target version | Related Epic   |
|--------------------|-----------------------|
|           4.6         |  wazuh/wazuh#17427             |

## Description 

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests dependencies from the `wazuh-qa` repository to the `qa-integration-framework` repository.

This specific issue aims to migrate all the dependencies used by the Active Response ITs.

### Tasks
- [x] Migrate & refactor **`CertificateController`**.
- [x] Add **`SimulatorInterface`** to use as base for all the simulators.
- [x] Migrate & refactor **`AuthSimulator`**.
- [x] Add **`SecureMessage`** class.
- [x] Migrate & refactor **`RemotedSImulator`**
- [x] Migrate and create utils for Active Response ITs

**Comment by QU3B1M** [comment]
### Update 08/06/2023

**Comment by QU3B1M** [comment]
Add generic interface for the simulators: 

```python

class SimulatorInterface(ABC):
    def __init__(self, server_ip: str, port: int) -> None:
        self.server_ip = server_ip
        self.port = port

    @abstractmethod
    def start():
        pass

    @abstractmethod
    def shutdown():
        pass
```

**Comment by QU3B1M** [comment]
- Completed **`AuthdSimulator`** and **`CertificateController`**

**Comment by QU3B1M** [comment]
- Add **`mode`** and **`running`** attributes to SimulatorInterface and its childs.
- Merge with main migration branch.
- Add Cipher class that handles cipher.
- Continue with migration of **`RemotedSimulator`**, it needs to be adapted to use **`ManInTheMiddle`**.
    > In its actual state the **`RemotedSimulator`** class is handling much more functionalities than it should, some may also need to be separated on another class, like a lot of encryption/decription that it does.

**Comment by QU3B1M** [comment]
- Minor fixes on the **`AuthdSimulator`**

**Comment by QU3B1M** [comment]
- Add **`keys.py`** utils to store functions related to `client.keys` or any generic keys generation.
- Move **`CertificateController`** from utils to tools.
- Add **`get_encrypted_payload`** function to **`Cipher`** that parses the _AES_ and _Blowfish_ encrypted messages.
- Continue with **`RemotedSimulator`** migration adding **`__get_agent_identifier`** function to get the connected agent identity.

**Comment by QU3B1M** [comment]
- Add **`SecureMessage`** class to handle wazuh secure messages encryption, encoding and parsing. It replaces `Cipher`
- Make **`RemotedSimulator`** use the `SecureMessage` class.
- Add **`keys.py`** utils to store all keys related functions.

**Comment by QU3B1M** [comment]
- Complete **`SecureMessage`** with utils functions

**Comment by QU3B1M** [comment]
- Merge `4157_tests_migration` to include last changes and fix conflicts
- Add docstrings to **`SecureMessage`**, **`RemotedSimulator`** and **`SimulatorInterface`**
- Improve variables naming on Simulators
- Move _encryption key generation_ and _pack/unpack_ functions to **`SecureMessage`**
- Add functionality in **`RemotedSimulator`** to wait for the custom message to be sent.
- Add `execd` and `active_response` modules
- Add new `logs` constants

**Comment by QU3B1M** [comment]
- Moved `SecureMessage` and `Certificate` from tools to utils.
- Add copyright and fix styling errors in all the affected files.
- Add patterns to `active_response`, `authd` and `execd` modules.
- Combine key.py with client_keys.py

**Comment by QU3B1M** [comment]
- Added patterns used by the `execd` Integration tests
