### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in qa-integration-framework repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/qa-integration-framework#257]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the qa-integration-framework repository.

## Tasks

- [ ] ~Delete previous Alpha 2 release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.10.0-alpha2.~
- [ ] ~Delete previous v4.10.0-alpha2 tag.~
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on qa-integration-framework repository.
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on qa-integration-framework repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.9.2-rc1.
