### ISSUE TITLE
Support new stage RC 2 for 4.7.0 in qa-integration-framework repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/qa-integration-framework#52]
## Description

This issue attempts to support a new stage RC 2 for 4.7.0 in the qa-integration-framework repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.0 (if applicable).
- [ ] Bump revision for branch 4.7.0 on qa-integration-framework repository.
- [ ] Create tag v4.7.0-rc2 from branch 4.7.0 on qa-integration-framework repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.7.0-rc2.

**Comment by Selutario** [comment]
Versioning is still to be defined.
