### ISSUE TITLE
Support new stage RC 1 for 4.7.1 in qa-integration-framework repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/qa-integration-framework#58]
## Description

This issue attempts to support a new stage RC 1 for 4.7.1 in the qa-integration-framework repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.1 (if applicable).
- [ ] Bump revision for branch 4.7.1 on qa-integration-framework repository.
- [x] Create tag v4.7.1-rc1 from branch 4.7.1 on qa-integration-framework repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.7.1-rc1.
