### ISSUE TITLE
Support new stage Alpha 1 for 4.8.0 in qa-integration-framework repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/qa-integration-framework#64]
## Description

This issue attempts to support a new stage Alpha 1 for 4.8.0 in the qa-integration-framework repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable).
- [x] Bump revision for branch 4.8.0 on qa-integration-framework repository.
- [x] Create tag v4.8.0-alpha1 from branch 4.8.0 on qa-integration-framework repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/qa-integration-framework/releases/tag/v4.8.0-alpha1.
